# --------------------- Custom params ---------------------
prompt_folder: prompts
user_prompt_name: base_think_user_prompt.jinja
system_prompt_name: base_think_system_prompt.jinja

# dataset load
dataset_name: null
add_test: true
validation_split: 0.2

# ----------------------------------------------------------

# batch size params:
gradient_accumulation_steps: 8
num_train_epochs: 5
per_device_eval_batch_size: 4
per_device_train_batch_size: 4


# Model arguments
model_name_or_path: null
model_revision: main
dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_num_proc: 2

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: "steps"
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: Qwen2.5-1.5B-Open-R1-Distill
hub_strategy: every_save
learning_rate: 1e-04
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_length: 8000  # Maximum length of the input sequence
# max_sequence_length: 1024  # TODO it does not work mf
# https://discuss.huggingface.co/t/no-skipping-steps-after-loading-from-checkpoint/6880/3
overwrite_output_dir: false
max_steps: -1
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_steps: 5 # must be equal to eval_steps otherwise error for loading the best model
eval_steps: 5
save_total_limit: 1
load_best_model_at_end: true
metric_for_best_model: "eval_loss"
seed: 42
warmup_ratio: 0.10
callbacks:
  early_stopping:
    early_stopping_patience: 3  # Number of evaluation steps with no improvement after which training will be stopped
    early_stopping_threshold: 0.01  # Minimum change in the monitored quantity to qualify as an improvement